mybatis-plus: #mybatis配置
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.xxgc.entity
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dfcms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    cache:false
server: #程序访问端口号
  port: 8081
  servlet:
    context-path: /cms